#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 11 20:54:11 2022

@author: lucas uchoa cruz saraiva
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

def plota_pivot_table(df, value, index, func, ylabel, xlabel, opcao='nada'):
    if opcao == 'nada':
        pd.pivot_table(df, values=value, index=index,
                       aggfunc=func).plot(figsize=[15, 5])
    elif opcao == 'sort':
        pd.pivot_table(df, values=value, index=index,
                       aggfunc=func).sort_values(value).plot(figsize=[15, 5])
    elif opcao == 'unstack':
        pd.pivot_table(df, values=value, index=index,
                       aggfunc=func).unstack().plot(figsize=[15, 5])
    plt.ylabel(ylabel)
    plt.xlabel(xlabel)
    return None

"""
mar = pd.read_csv('./input/SINASC_RO_2019_MAR.csv')
print(mar.DTNASC.min(), mar.DTNASC.max())

abr = pd.read_csv('./input/SINASC_RO_2019_ABR.csv')
print(abr.DTNASC.min(), abr.DTNASC.max())

mai = pd.read_csv('./input/SINASC_RO_2019_MAI.csv')
print(mai.DTNASC.min(), mai.DTNASC.max())

jun = pd.read_csv('./input/SINASC_RO_2019_JUN.csv')
print(jun.DTNASC.min(), jun.DTNASC.max())

dez = pd.read_csv('./input/SINASC_RO_2019_DEZ.csv')
print(dez.DTNASC.min(), dez.DTNASC.max())
"""
meses = ['mar','abr','mai','jun','dez'] # lista dos meses

for mes in meses:

    mes = pd.read_csv('./input/SINASC_RO_2019_'+mes.upper()+'.csv')
#    print(mes.DTNASC.min(), mes.DTNASC.max())

    max_data = mes.DTNASC.max()[:7]
    print(max_data)
    os.makedirs('./figs/'+max_data, exist_ok=True)
#----------------------------------------------------------------------------------------------    
    plota_pivot_table(mes, 'IDADEMAE', 'DTNASC', 'count', 'quantidade de nascimento','data de nascimento')
    plt.savefig('./figs/'+max_data+'/quantidade de nascimento.png')
#----------------------------------------------------------------------------------------------
    plota_pivot_table(mes, 'IDADEMAE', ['DTNASC', 'SEXO'], 'mean', 'media idade mae','data de nascimento',
                      'unstack')
    plt.savefig('./figs/'+max_data+'/media idade mae por sexo.png')
#----------------------------------------------------------------------------------------------
    plota_pivot_table(mes, 'PESO', ['DTNASC', 'SEXO'], 'mean', 'media peso bebe','data de nascimento',
                      'unstack')
    plt.savefig('./figs/'+max_data+'/media peso bebe por sexo.png')
#----------------------------------------------------------------------------------------------
    plota_pivot_table(mes, 'PESO', 'ESCMAE', 'median', 'apgar1 medio','gestacao','sort')
    plt.savefig('./figs/'+max_data+'/media apgar1 por escolaridade mae.png')
#----------------------------------------------------------------------------------------------
    plota_pivot_table(mes, 'APGAR1', 'GESTACAO', 'mean', 'apgar1 medio','gestacao','sort')
    plt.savefig('./figs/'+max_data+'/media apgar1 por gestacao.png')
#----------------------------------------------------------------------------------------------
    plota_pivot_table(mes, 'APGAR5', 'GESTACAO', 'mean', 'apgar5 medio','gestacao','sort')
    plt.savefig('./figs/'+max_data+'/media apgar5 por gestacao.png')
#----------------------------------------------------------------------------------------------


